### ISSUE TITLE
Crash on android when using with "audio_service"

### ISSUE THREAD

**Issue by creative-hustlers** [Web3Auth/web3auth-flutter-sdk#20]
When using this plugin along with "audio_service" plugin it will crash when we click on notification music player and shows following log
    

```
kotlin.UninitializedPropertyAccessException: lateinit property web3auth has not been initialized
        at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin.onNewIntent(Web3AuthFlutterPlugin.kt:65)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent(FlutterEngineConnectionRegistry.java:830)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent(FlutterEngineConnectionRegistry.java:446)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent(FlutterActivityAndFragmentDelegate.java:772)
        at io.flutter.embedding.android.FlutterActivity.onNewIntent(FlutterActivity.java:733)
        at android.app.Activity.performNewIntent(Activity.java:8306)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1429)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1442)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4241)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4248)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

It seems it is related with following issue
https://github.com/ryanheise/audio_service/issues/919

**Comment by shahbaz17** [comment]
Hey @creative-hustlers 

Could you try again with the latest SDK? Also, it looks like the issue is with the other package.

We do have an android-web3auth example https://github.com/Web3Auth/examples/tree/main/android. Please try any of the apps and see if it works with your configs. 

I'm really looking forward to learning more about this bug.

**Comment by grvgoel81** [comment]
Please try with latest sdk version. It is resolved.
