### ISSUE TITLE
App crashing after deep linking

### ISSUE THREAD

**Issue by AniketSindhu** [Web3Auth/web3auth-flutter-sdk#29]
If the app is opened with any deeplink other than web3auth's one. App crashes with logs below. It may be because the library is trying to process the link not made for it.

```
D/AndroidRuntime( 9688): Shutting down VM
E/AndroidRuntime( 9688): FATAL EXCEPTION: main
E/AndroidRuntime( 9688): Process: com.naan, PID: 9688
E/AndroidRuntime( 9688): kotlin.UninitializedPropertyAccessException: lateinit property web3auth has not been initialized
E/AndroidRuntime( 9688): 	at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin.onNewIntent(Web3AuthFlutterPlugin.kt:65)
E/AndroidRuntime( 9688): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent(FlutterEngineConnectionRegistry.java:830)
E/AndroidRuntime( 9688): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent(FlutterEngineConnectionRegistry.java:446)
E/AndroidRuntime( 9688): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent(FlutterActivityAndFragmentDelegate.java:777)
E/AndroidRuntime( 9688): 	at io.flutter.embedding.android.FlutterFragment.onNewIntent(FlutterFragment.java:932)
E/AndroidRuntime( 9688): 	at io.flutter.embedding.android.FlutterFragmentActivity.onNewIntent(FlutterFragmentActivity.java:536)
E/AndroidRuntime( 9688): 	at android.app.Activity.performNewIntent(Activity.java:8067)
E/AndroidRuntime( 9688): 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1429)
E/AndroidRuntime( 9688): 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1442)
E/AndroidRuntime( 9688): 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3832)
E/AndroidRuntime( 9688): 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3839)
E/AndroidRuntime( 9688): 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
E/AndroidRuntime( 9688): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 9688): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 9688): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 9688): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
E/AndroidRuntime( 9688): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9688): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 9688): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 9688): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 9688): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9688): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 9688): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process ( 9688): Sending signal. PID: 9688 SIG: 9
Lost connection to device.
Exited
```

**Comment by grvgoel81** [comment]
Hi, This issue has been resolved.
