### ISSUE TITLE
lateinit property sharedPreferences has not been initialized

### ISSUE THREAD

**Issue by yq-ftadini** [Web3Auth/web3auth-flutter-sdk#46]
Hi,
I'm facing the following errors on Android devices, during Web3Auth login. 
For the first one, MFA disabled for Web3Auth, the login process seems to be completed well, but at the momento I'm not able to understand if there are side effects.
For the second one, MFA enabled, the result is the app crash.

#### Error 1
```
W/System.err(15700): kotlin.UninitializedPropertyAccessException: lateinit property sharedPreferences has not been initialized
W/System.err(15700): 	at com.web3auth.core.keystore.KeyStoreManagerUtils.decryptData(KeyStoreManagerUtils.kt:85)
W/System.err(15700): 	at com.web3auth.core.Web3Auth.login(Web3Auth.kt:138)
W/System.err(15700): 	at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin.runMethodCall(Web3AuthFlutterPlugin.kt:115)
W/System.err(15700): 	at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin.access$runMethodCall(Web3AuthFlutterPlugin.kt:30)
W/System.err(15700): 	at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin$onMethodCall$1.invokeSuspend(Web3AuthFlutterPlugin.kt:76)
W/System.err(15700): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(15700): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err(15700): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W/System.err(15700): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err(15700): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W/System.err(15700): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

#### Error 2
```
W/System.err(15700): kotlin.UninitializedPropertyAccessException: lateinit property sharedPreferences has not been initialized
W/System.err(15700): 	at com.web3auth.core.keystore.KeyStoreManagerUtils.decryptData(KeyStoreManagerUtils.kt:85)
W/System.err(15700): 	at com.web3auth.core.Web3Auth.login(Web3Auth.kt:138)
W/System.err(15700): 	at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin.runMethodCall(Web3AuthFlutterPlugin.kt:115)
W/System.err(15700): 	at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin.access$runMethodCall(Web3AuthFlutterPlugin.kt:30)
W/System.err(15700): 	at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin$onMethodCall$1.invokeSuspend(Web3AuthFlutterPlugin.kt:76)
W/System.err(15700): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(15700): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err(15700): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W/System.err(15700): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err(15700): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W/System.err(15700): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
D/com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin(15700): #login
I/flutter (15700): 228
I/FLTFireMsgService(15700): FlutterFirebaseMessagingBackgroundService started!
E/BLASTBufferQueue(15700): BLASTBufferItemConsumer::onDisconnect()
E/BLASTBufferQueue(15700): BLASTBufferItemConsumer::onDisconnect()
I/FA      (15700): Application backgrounded at: timestamp_millis: 1686733567333
D/ProfileInstaller(15700): Installing profile for it.youthquake.mine
D/AndroidRuntime(15700): Shutting down VM
E/AndroidRuntime(15700): FATAL EXCEPTION: main
E/AndroidRuntime(15700): Process: it.youthquake.mine, PID: 15700
E/AndroidRuntime(15700): kotlin.UninitializedPropertyAccessException: lateinit property sharedPreferences has not been initialized
E/AndroidRuntime(15700): 	at com.web3auth.core.keystore.KeyStoreManagerUtils.encryptData(KeyStoreManagerUtils.kt:62)
E/AndroidRuntime(15700): 	at com.web3auth.core.Web3Auth.setResultUrl(Web3Auth.kt:123)
E/AndroidRuntime(15700): 	at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin.onNewIntent(Web3AuthFlutterPlugin.kt:68)
E/AndroidRuntime(15700): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent(FlutterEngineConnectionRegistry.java:834)
E/AndroidRuntime(15700): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent(FlutterEngineConnectionRegistry.java:450)
E/AndroidRuntime(15700): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent(FlutterActivityAndFragmentDelegate.java:842)
E/AndroidRuntime(15700): 	at io.flutter.embedding.android.FlutterActivity.onNewIntent(FlutterActivity.java:926)
E/AndroidRuntime(15700): 	at android.app.Activity.performNewIntent(Activity.java:8145)
E/AndroidRuntime(15700): 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1444)
E/AndroidRuntime(15700): 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1457)
E/AndroidRuntime(15700): 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3982)
E/AndroidRuntime(15700): 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3989)
E/AndroidRuntime(15700): 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
E/AndroidRuntime(15700): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(15700): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(15700): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(15700): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
E/AndroidRuntime(15700): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15700): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(15700): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(15700): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(15700): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15700): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(15700): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
I/Process (15700): Sending signal. PID: 15700 SIG: 9
Lost connection to device.
```

Thanks
Kind regards

**Comment by grvgoel81** [comment]
Resolved in PR https://github.com/Web3Auth/web3auth-flutter-sdk/pull/47
