### ISSUE TITLE
Lateinit property sharedPreferences has not been initialized

### ISSUE THREAD

**Issue by binhdowkm** [Web3Auth/web3auth-flutter-sdk#70]
**Steps to reproduce**

1. web3auth_flutter: 3.1.7 
2. Set up follow official document, iOS work well. But on Android, functions `login`, `logout`, `setResultUrl`, ... cause crash on some device.
3. App crash immediately after

**Logs**

```console
E/AndroidRuntime(27147): com.web3auth.jp2: lateinit property sharedPreferences has not been initialized
E/AndroidRuntime(27147):        at com.web3auth.session_manager_android.keystore.KeyStoreManager.savePreferenceData(Unknown Source:16)
E/AndroidRuntime(27147):        at com.web3auth.session_manager_android.SessionManager.saveSessionId(Unknown Source:18)
E/AndroidRuntime(27147):        at com.web3auth.core.Web3Auth.setResultUrl(Unknown Source:104)
E/AndroidRuntime(27147):        at com.web3auth.flutter.web3auth_flutter.Web3AuthFlutterPlugin.onNewIntent(Unknown Source:21)
E/AndroidRuntime(27147):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent(Unknown Source:18)
E/AndroidRuntime(27147):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent(Unknown Source:14)
E/AndroidRuntime(27147):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent(Unknown Source:20)
E/AndroidRuntime(27147):        at io.flutter.embedding.android.FlutterFragment.onNewIntent(Unknown Source:10)
E/AndroidRuntime(27147):        at io.flutter.embedding.android.FlutterFragmentActivity.onNewIntent(Unknown Source:2)
E/AndroidRuntime(27147):        at android.app.Activity.performNewIntent(Activity.java:8908)
E/AndroidRuntime(27147):        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1570)
E/AndroidRuntime(27147):        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1583)
E/AndroidRuntime(27147):        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4207)
E/AndroidRuntime(27147):        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4214)
E/AndroidRuntime(27147):        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
E/AndroidRuntime(27147):        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(27147):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/AndroidRuntime(27147):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
E/AndroidRuntime(27147):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2612)
E/AndroidRuntime(27147):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27147):        at android.os.Looper.loopOnce(Looper.java:222)
E/AndroidRuntime(27147):        at android.os.Looper.loop(Looper.java:314)
E/AndroidRuntime(27147):        at android.app.ActivityThread.main(ActivityThread.java:8670)
E/AndroidRuntime(27147):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27147):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
E/AndroidRuntime(27147):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

```

**Smartphone**
 - Device: Samsung S21 Ultra, Xiaomi 11T
 - OS: Android 14

**Additional context**
- Problem happen when build `release`
```
        release {
            signingConfig signingConfigs.release

            minifyEnabled true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```

❤️ Thanks!

**Comment by binhdowkm** [comment]
I found some issue about that `EncryptedSharedPreferences` is using in [session-manager-android](https://github.com/Web3Auth/session-manager-android/blob/master/session-manager-android/src/main/java/com/web3auth/session_manager_android/keystore/KeyStoreManager.kt) is the reason cause app crash.
Follow https://github.com/tink-crypto/tink/issues/535. I try 

```
android:allowBackup="false"
android:fullBackupContent="false"
```

But  [web3auth-android-sdk](https://github.com/Web3Auth/web3auth-android-sdk/blob/master/core/src/main/AndroidManifest.xml) is using
```
android:allowBackup="true"
```
Its conflict with solution before, so I fixed it and finally I have
```
android:allowBackup="false"
tools:replace="android:allowBackup"
android:fullBackupContent="false"
android:dataExtractionRules="@xml/data_extraction_rules"
tools:targetApi="tiramisu"
```
And do not use `android.enableR8.fullMode=true` on `gradle.properties`

**Finally, it solved my problem**

But, can you explain to me why it happens?

**Comment by grvgoel81** [comment]
This is resolved in latest release.
